<wsdl:definitions
     name="PollerDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TestSoaApp/Poller/PollerDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TestSoaApp/Poller/PollerDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollerDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="PollerDB_plt" >
    <plt:role name="PollerDB_role" >
      <plt:portType name="tns:PollerDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollerDB" schemaLocation="../Schemas/PollerDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="PollTableCollection_msg">
        <wsdl:part name="PollTableCollection" element="top:PollTableCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollerDB_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:PollTableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
